# Generated by Django 4.1.1 on 2023-11-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pf_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
