# Generated by Django 4.1.1 on 2023-11-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pf_contact',
            name='status',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
